### ISSUE TITLE
Front tag

### ISSUE THREAD

**Issue by rasuljasirdent** [DEFI-COLaF/metadata#27]
Hi @Juliettejns, I've tried to add a front element for a play and it looks like the tag is not in the ODD.

![image](https://github.com/user-attachments/assets/cbfa6c0f-fc4d-4193-bec6-4cd1f448464b)

**Comment by Juliettejns** [comment]
Hi Rasul! 
For the time being, we are not using front in the COLaF ODD.
You will find an example showing how it's supposed to be done here : https://github.com/DEFI-COLaF/Datasets_text/blob/moliest/Moliest/pipeline/Pattern_Simple_XML.xml#L110 
Do not hesitate to refer to that document, I did it so that you have a pattern for play encoding:)
